blueprint:
    name: Sound Detection with LED Control
    description: Turn on light based on sound detecion
    domain: automation

trigger:
  platform: state
  entity_id: sensor.sound_detection

action:
    service: >
      {% if trigger.to_state.state == "Sound Detected" %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    target:
      entity_id: switch.led_control