blueprint:
  name: Sound Detection with Crib Control
  description: Turn on crib rocker based on sound detection
  domain: automation

trigger:
  platform: state
  entity_id: sensor.sound_detection

action:
  service: >
    {% if trigger.to_state.state == "Sound Detected" and is_state('input_boolean.crib_control', 'on') %}
      switch.turn_on
    {% else %}
      switch.turn_off
    {% endif %}
  target:
    entity_id: switch.crib_control
